import Head from 'next/head'
import Image from 'next/image'
import bg1 from '../public/bg1.png'
import bg2 from '../public/bg2.png'

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<div className='bg-cover bg-center bg-no-repeat h-screen w-screen bg-green-500 -z-20 relative overflow-hidden flex items-center justify-center'>
					<Image
						src={bg1}
						layout='fill'
						object-fit='cover'
						className='absolute h-full w-full -z-10'
						alt='/'
					/>
					<div className='px-8 py-4 absolute bg-white top-36 border-8 border-[#E5E5E5] bg-opacity-50  '>
						<h1>Wednesday</h1>
					</div>
					<div className='px-8 py-4 absolute top-80 bg-[#D9D9D9] rounded-full '>
						<h2>Sign up</h2>
					</div>
				</div>
				<div className='bg-cover bg-center bg-no-repeat h-screen w-screen bg-red-500 relative overflow-hidden'>
					<Image
						src={bg2}
						layout='fill'
						object-fit='cover'
						className='absolute h-full w-full'
						alt='/'
					/>
          
				</div>
			</main>
		</div>
	)
}
